spring:
  application:
    name: kafka-bq-performance
  main:
    allow-bean-definition-overriding: true
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# Common BigQuery Configuration
bigquery:
  project-id: ${BQ_PROJECT_ID:your-gcp-project-id}
  dataset: ${BQ_DATASET:your_dataset}
  table: ${BQ_TABLE:your_table}
  credentials-path: ${BQ_CREDENTIALS_PATH:/path/to/your/credentials.json}

# Kafka Topics Configuration
kafka:
  topic: ${KAFKA_TOPIC:test-topic}
  
# Default Performance Configuration
performance:
  batch-size: ${BATCH_SIZE:1000}
  flush-interval-ms: ${FLUSH_INTERVAL_MS:5000}
  
# Default Logging Configuration
logging:
  level:
    root: INFO
    com.example.kafkabqperformance: INFO
    org.apache.kafka: WARN
