# Configuration for running without Kafka (fake messages only)
spring:
  application:
    name: kafka-bq-performance
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  kafka:
    bootstrap-servers: dummy:9092
    consumer:
      group-id: dummy-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8081
      
# BigQuery Configuration - Local Development
bigquery:
  project-id: jovial-engine-458300-n6
  dataset: kafka_bq_transactions
  table: kafka_messages
  credentials-path: ./config/gcp-credentials.json

# Performance Configuration
performance:
  batch-size: 100  # Smaller batch for local testing
  flush-interval-ms: 5000
  
# Logging Configuration
logging:
  level:
    root: INFO
    com.example.kafkabqperformance: DEBUG
    org.springframework.kafka: ERROR
    com.google.cloud.bigquery: DEBUG
    com.google.api.client.http: DEBUG
    com.google.cloud: DEBUG 