apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-bq-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: kafka-bq-app
  template:
    metadata:
      labels:
        app: kafka-bq-app
    spec:
      containers:
        - name: kafka-bq-container
          image: us-docker.pkg.dev/PROJECT_ID/kafka-bq-images/kafka-bq-performance:VERSION
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/app/credentials/credentials.json"
          volumeMounts:
            - name: bigquery-credentials
              mountPath: "/app/credentials"
              readOnly: true
            - name: app-config
              mountPath: "/app/config/application-prod.properties"
              subPath: application-prod.properties
              readOnly: true
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
      volumes:
        - name: bigquery-credentials
          secret:
            secretName: bigquery-credentials
        - name: app-config
          configMap:
            name: kafka-bq-config
