name: Build and Deploy to GKE

on:
  push:
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  IMAGE: kafka-bq-performance
  REGION: us
  REPO: kafka-bq-images
  BQ_PROJECT_ID: ${{ secrets.BQ_PROJECT_ID }}
  BQ_DATASET: ${{ secrets.BQ_DATASET }}
  BQ_TABLE: ${{ secrets.BQ_TABLE }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker us-docker.pkg.dev --quiet

    - name: Build and Push Docker Image to Artifact Registry
      run: |
        docker build -t us-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:$GITHUB_SHA .
        docker push us-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:$GITHUB_SHA

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Create BigQuery credentials Secret
      run: |
        echo '${{ secrets.BQ_CREDENTIALS }}' > credentials.json
        kubectl delete secret bigquery-credentials --ignore-not-found
        kubectl create secret generic bigquery-credentials --from-file=credentials.json=credentials.json
        rm credentials.json

    - name: Apply ConfigMap
      run: |
        sed -i.bak "s|\${BQ_PROJECT_ID}|${BQ_PROJECT_ID}|g" ./k8s/configmap.yaml
        sed -i.bak "s|\${BQ_DATASET}|${BQ_DATASET}|g" ./k8s/configmap.yaml
        sed -i.bak "s|\${BQ_TABLE}|${BQ_TABLE}|g" ./k8s/configmap.yaml
        kubectl apply -f ./k8s/configmap.yaml
        rm ./k8s/configmap.yaml.bak

    - name: Replace image tag in deployment.yaml
      run: |
        sed -i.bak "s|us-docker.pkg.dev/PROJECT_ID/kafka-bq-images/kafka-bq-performance:VERSION|us-docker.pkg.dev/$PROJECT_ID/$REPO/$IMAGE:$GITHUB_SHA|g" ./k8s/deployment.yaml

    - name: Deploy to GKE
      run: |
        kubectl apply -f ./k8s/deployment.yaml
        kubectl apply -f ./k8s/service.yaml
        echo "Waiting for pods to be created..."
        sleep 30
        echo "Pod status:"
        kubectl get pods -l app=kafka-bq-app -o wide
        echo "\nPod description:"
        kubectl describe pods -l app=kafka-bq-app
        echo "\nAttempting rollout status with timeout:"
        timeout 60s kubectl rollout status deployment/kafka-bq-deployment || true
        echo "\nChecking container logs (if any):"
        POD_NAME=$(kubectl get pods -l app=kafka-bq-app -o jsonpath='{.items[0].metadata.name}' 2>/dev/null) || true
        if [ -n "$POD_NAME" ]; then
          kubectl logs $POD_NAME --all-containers=true || true
        fi
        rm ./k8s/deployment.yaml.bak

    - name: Get External IP
      run: |
        echo "Waiting for external IP..."
        for i in {1..20}; do
          IP=$(kubectl get svc kafka-bq-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          if [[ -n "$IP" ]]; then
            echo "Service available at: http://$IP"
            exit 0
          fi
          sleep 10
        done
        echo "Failed to retrieve external IP after waiting."
        exit 1
